defaults:
- config_schema
- model: dann
- _self_

hydra:
  job:
    chdir: True

dataset:
  n_datapoints: 10000
  n_test_datapoints: 1000
  n: 200
  k: 20
  batch_size: 500
project_results_dir: "/network/projects/_groups/linclab_users/danns/subprojects/eg"
opt:
  use_sep_inhib_lrs: False
  update_algorithm: "eg"
  lr: 0.1
  wd: 0
  momentum: 0
# output_dir: "${SLURM_TMPDIR}"
# hydra:
#   run:
#     dir: "${SLURM_TMPDIR}"