dataset:
  n_datapoints: 1000
  n: 10
  k: 2
  batch_size: 200
model: "dann"

project_results_dir: "/network/projects/_groups/linclab_users/danns/subprojects/eg"
opt:
  use_sep_inhib_lrs: False
  update_algorithm: "eg"
  lr: 0.1
  wd: 0
  momentum: 0
# output_dir: "${SLURM_TMPDIR}"
# hydra:
#   run:
#     dir: "${SLURM_TMPDIR}"