defaults:
- model: dann
- _self_

# model:
#   name: override_value_here

hydra:
  job:
    chdir: True
n_epochs:
  30
dataset:
  n_datapoints: 10000
  n_test_datapoints: 1000
  n: 20000
  k: 20
  batch_size: 500
project_results_dir: "/network/projects/_groups/linclab_users/danns/subprojects/eg"
opt:
  update_algorithm: "eg"
  lr: 1
  wd: 0
  momentum: 0
# output_dir: "${SLURM_TMPDIR}"
# hydra:
#   run:
#     dir: "${SLURM_TMPDIR}"